#application:
#  servlet-path: /zdtMobile/*
# \u5E94\u7528\u670D\u52A1 WEB \u8BBF\u95EE\u7AEF\u53E3
server:
  port: 8081
  servlet:
    context-path: zdtMobile
# \u5E94\u7528\u540D\u79F0
spring:
  application:
    name: zdtMobile
#\u6570\u636E\u6E90\u914D\u7F6E
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.24.65.204:3306/prod?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: prod
    password: prod
    druid:
      # \u8FDE\u63A5\u6C60\u7684\u914D\u7F6E\u4FE1\u606F
      # \u521D\u59CB\u5316\u5927\u5C0F\uFF0C\u6700\u5C0F\uFF0C\u6700\u5927
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # \u914D\u7F6E\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u7684\u65F6\u95F4
      maxWait: 60000
      # \u914D\u7F6E\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
      timeBetweenEvictionRunsMillis: 60000
      # \u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u7684\u65F6\u95F4\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # \u6253\u5F00PSCache\uFF0C\u5E76\u4E14\u6307\u5B9A\u6BCF\u4E2A\u8FDE\u63A5\u4E0APSCache\u7684\u5927\u5C0F
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # \u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters\uFF0C\u53BB\u6389\u540E\u76D1\u63A7\u754C\u9762sql\u65E0\u6CD5\u7EDF\u8BA1\uFF0C'wall'\u7528\u4E8E\u9632\u706B\u5899
      filters: stat,wall,slf4j
      # \u901A\u8FC7connectProperties\u5C5E\u6027\u6765\u6253\u5F00mergeSql\u529F\u80FD\uFF1B\u6162SQL\u8BB0\u5F55
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
    #redis \u914D\u7F6E
    redis:
      database: 0
      host: 127.0.0.1
      lettuce:
        pool:
          max-active: 8   #\u6700\u5927\u8FDE\u63A5\u6570\u636E\u5E93\u8FDE\u63A5\u6570,\u8BBE 0 \u4E3A\u6CA1\u6709\u9650\u5236
          max-idle: 8     #\u6700\u5927\u7B49\u5F85\u8FDE\u63A5\u4E2D\u7684\u6570\u91CF,\u8BBE 0 \u4E3A\u6CA1\u6709\u9650\u5236
          max-wait: -1ms  #\u6700\u5927\u5EFA\u7ACB\u8FDE\u63A5\u7B49\u5F85\u65F6\u95F4\u3002\u5982\u679C\u8D85\u8FC7\u6B64\u65F6\u95F4\u5C06\u63A5\u5230\u5F02\u5E38\u3002\u8BBE\u4E3A-1\u8868\u793A\u65E0\u9650\u5236\u3002
          min-idle: 0     #\u6700\u5C0F\u7B49\u5F85\u8FDE\u63A5\u4E2D\u7684\u6570\u91CF,\u8BBE 0 \u4E3A\u6CA1\u6709\u9650\u5236
        shutdown-timeout: 100ms
      password: ''
      port: 6379
#mybatis-plus\u914D\u7F6E
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.zdt.module.entity
  global-config:
    # \u5173\u95EDMP3.0\u81EA\u5E26\u7684banner
    banner: false
    db-config:
      #\u4E3B\u952E\u7C7B\u578B  0:"\u6570\u636E\u5E93ID\u81EA\u589E",1:"\u8BE5\u7C7B\u578B\u4E3A\u672A\u8BBE\u7F6E\u4E3B\u952E\u7C7B\u578B", 2:"\u7528\u6237\u8F93\u5165ID",3:"\u5168\u5C40\u552F\u4E00ID (\u6570\u5B57\u7C7B\u578B\u552F\u4E00ID)", 4:"\u5168\u5C40\u552F\u4E00ID UUID",5:"\u5B57\u7B26\u4E32\u5168\u5C40\u552F\u4E00ID (idWorker \u7684\u5B57\u7B26\u4E32\u8868\u793A)";
      id-type: ID_WORKER
      #\u5B57\u6BB5\u7B56\u7565 IGNORED:"\u5FFD\u7565\u5224\u65AD"  NOT_NULL:"\u975E NULL \u5224\u65AD")  NOT_EMPTY:"\u975E\u7A7A\u5224\u65AD"
      field-strategy: NOT_EMPTY
      # \u9ED8\u8BA4\u6570\u636E\u5E93\u8868\u4E0B\u5212\u7EBF\u547D\u540D
      table-underline: true
      db-type: mysql
    #\u5237\u65B0mapper \u8C03\u8BD5\u795E\u5668
    refresh: true
    configuration:
      # \u8FD9\u4E2A\u914D\u7F6E\u4F1A\u5C06\u6267\u884C\u7684sql\u6253\u5370\u51FA\u6765\uFF0C\u5728\u5F00\u53D1\u6216\u6D4B\u8BD5\u7684\u65F6\u5019\u53EF\u4EE5\u7528
      #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      # \u8FD4\u56DE\u7C7B\u578B\u4E3AMap,\u663E\u793Anull\u5BF9\u5E94\u7684\u5B57\u6BB5
      call-setters-on-nulls: true
# jasypt\u52A0\u5BC6\u79D8\u94A5\uFF0C\u8BE5\u79D8\u94A5\u53EF\u4EE5\u81EA\u5B9A\u4E49
jasypt:
  encryptor:
    password: zdt
    # \u6307\u5B9A\u52A0\u5BC6\u65B9\u5F0F
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
#日志
ZSMART_HOME: D:/logs
#httpClient配置
http:
  #设置连接总数
  maxTotal: 500
  #设置每个主机最大的并发数
  defaultMaxPerRoute: 100
  #设置创建连接的最长时间
  connectTimeout: 2000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
  #数据传输的最长时间
  socketTimeout: 6000
  #空闲时间(用于定期清理空闲连接)
  maxIdleTime: 1
#Xss攻击拦截配置
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /zdtMobile/*
  # 匹配链接
  urlPatterns: /*
#csrf攻击拦截配置
csrf:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /zdtMobile/login
  # 匹配链接
  urlPatterns: /*